# Generated by Django 3.0.2 on 2020-06-01 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
        ('analytics', '0002_usersession'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=220, null=True)),
                ('count', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shortener.CondenseURL')),
            ],
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='user',
        ),
        migrations.DeleteModel(
            name='ObjectViewed',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
