# Generated by Django 3.0.2 on 2020-06-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20200601_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urlviews',
            options={'verbose_name': 'Url View'},
        ),
        migrations.AlterField(
            model_name='urlviews',
            name='ip_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
